app = 'remix-prod-reports'
primary_region = 'cdg'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
